# Site settings
title: "Hello internet"
email: asbraithwaite(…ê)gmail.com
twitter: caust1c
description: "An exercise in documentation."
baseurl: ""
url: "https://abraithwaite.net"
username: abraithwaite

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

segment_analytics: jqZVsJ0WxrT7aAUjaa01cOIOHAucVLIs
