# Site settings
title: "Hello internet"
email: asbraithwaite(…ê)gmail.com
description: "An exercise in documentation."
baseurl: ""
url: "http://abraithwaite.github.io"
username: abraithwaite

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

google_analytics: UA-96367067-1
mixpanel_analytics: 9bbb9cedd693284c189817fbe0371144
quantcast_analytics: p-Rjzx13NLfLJZT
segment_analytics: jqZVsJ0WxrT7aAUjaa01cOIOHAucVLIs
yandex_analytics: 43802359
